### PR TITLE
feat: nix flake setup

### PR DESCRIPTION
**Pull request by dpc**
Add `flake.nix` (and friends) to help Nix user develop, compile and use this project.

You can read more about Nix Flakes:

https://www.tweag.io/blog/2020-05-25-flakes/

### CODE REVIEW

**Comment by dpc** [comment]
This can be tested with `nix run 'github:dpc/fpush?rev=dce498c63c1258ac13aeecee9e6786789f692346'` (or whatever is the commit of my PR, in case I force push it later), and after landing `nix run 'github:monal-im/fpush'` just work.

**Comment by FriedrichAltheide** [comment]
Thank you very much. As neither @tmolitor-stud-tu  nor I are nix users, we have a few questions that need to be answered.

1.	Can the nix files be placed in a subfolder instead of root?
2.	How can we inform nix users that neither @tmolitor-stud-tu  nor I maintain the nix build files?
3.	Are you going to maintain these packages/build files in the long run?
4.	What version number scheme would be required? Currently there is none, as we do not package any release publicly.


And some questions independent from your PR out of curiosity.
•	How are you planning to use fpush?
•	What is your experience so far, have you encountered any bugs / glitches?
Would be great to get some feedback either within this PR or via mail: info@monal-im.org

**Comment by dpc** [comment]
1. Kind of, but not really (flake.nix could be in a subdir, but this creates bunch of issues). 
2. A shell hook could be added to print when entering the nix develop shell, but it's easy to overlook. So not a silver bullet.
3. Unless you plan to increase the scope drastically this file shouldn't require lots of maintenance(TM). As long we're using fpush, I'm planning to maintain it for our own use, but that might be only until the end of the year.
4. It should follow (and even auto-detect) versioning from Cargo.toml

All in all, I have no problem if you do not wish to merge it. I already had it, so it made sense to create a PR.

> How are you planning to use fpush?

We've set up push notifications from XMPP server to Android devices, I think. I only did the Nixification part.

> What is your experience so far, have you encountered any bugs / glitches?

As far I know everything was fine. :+1:

**Comment by FriedrichAltheide** [comment]
@tmolitor-stud-tu reminder that we should discuss merging this PR at our next meeting

**Pull request merged**
